#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VehicleManageApp.Droid.Resource", IsApplication=true)]

namespace VehicleManageApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alert2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int call = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int call2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int carsacn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int carsafe = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int carscan2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int carscan3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chart = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int clock = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int clock2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dandrive = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dandrive2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fast = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int gasolin = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int gasolin2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int locate = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int locate2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int monoandroidsplash = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int people = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int safe = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int safe2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int search = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int trace = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int trace2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int vehicle = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public const int Mono_Android_Theme_Splash = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
